### ISSUE TITLE
Add inclusive low/high results

### ISSUE THREAD

**Issue by robrez** [jddamore/HL7-Task-Force-Examples#19]
It would be helpful to add examples where the result is
- less-than _or equal to_ 
- greater-than _or equal to_

A given value. Example currently have non-inclusive low/high (assuming the default value for the inclusive attribute is false).

_edit_: The mdht docs state that the default value for `inclusive` is `true`... If that is accurate then the current examples (for greater/less-than should have an explicit `inclusive="false"`).
[IVXB_PQ docs](http://cdatools.org/javadoc/org/openhealthtools/mdht/uml/hl7/datatypes/IVXB_PQ.html)

I think they would be something like this..

```
          <value xsi:type="IVL_PQ">
            <!-- The lower bound represents the minimum value based on lab result-->
            <low value="500" unit="mg/dL" inclusive="true"/>
            <!-- The upper bound is set to nullFlavor of positive infinity since it could be any number greater than 500-->
            <high nullFlavor="PINF"/>
          </value>
```

**Comment by jddamore** [comment]
Rob,

If you can join the HL7 Example Task Force (which is volunteer) call today
@ noon (it's generally Thursday 12pm ET), this is something you could
suggest. If you'd like to make the sample and maintain a link on GitHub,
you can author and send to Brett who leads the group (he is a HL7 SDWG
chair). If you don't want to author, I can add it to the hopper, although
I've got a long list of samples people want me to make.

That said, it's a good idea, although I think Rob Hausem from HL7 had some
thoughts about boundaries with inclusive (but it was a year ago, so I can't
quite remember what).

Cheers,
John

**Comment by robrez** [comment]
Thanks John,

I'll look into that Task Force call.

_ps_ I was thinking that it would probably suffice to simply modify one of the existing examples to use an inclusive boundary.

**Comment by jddamore** [comment]
It's public and we're always looking for more peeps to help. Here's info if
you're interested
http://lists.hl7.org/read/messages?id=282550#282550

**Comment by robrez** [comment]
Thanks, I was just now trying to find the phone# on the hl7 website

**Comment by jddamore** [comment]
There's one out in official CDA search tool now from HL7. Closing issue: 
http://cdasearch.hl7.org/examples/view/5acc416e7ad6fae1546c561cfc216eae8fb655de
